# Generated by Django 3.0.7 on 2020-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0002_auto_20200605_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
